# Dependencies
markdown:            redcarpet
redcarpet:
    extensions: [with_toc_data, footnotes]
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               LA Open Data
tagline:             'Policy and Playbook'
description:         'Draft Open Data Policy and Playbook from the Los Angeles Data Team'
url:                 http://datala.github.com
baseurl:             /od-policy/
paginate:            5

# About/contact
author:
  name:              Abhi Nemani
  url:               https://twitter.com/abhinemani
  email:             abhi.nemani@lacity.org

# Custom vars
version:             2.0.0
