# Dependencies
markdown:            redcarpet
redcarpet:
    extensions: [with_toc_data, footnotes]
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               CITY OF WEST HOLLYWOOD INNOVATIONS
tagline:             'ANNUAL REPORT 2015'
description:         'Inagural report on innovations from the WeHoX Team'
url:                 http://datala.github.com
baseurl:             /2015-report/
paginate:            5

# About/contact
author:
  name:              WeHoX
  url:               https://wehox.org
  email:             

# Custom vars
version:             2.0.0
